services:
  spring-boot-app:
    container_name: gpc-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080
    volumes:
      - ./resources:/GPC-APP/resources

#  frontend:
#    container_name: react-app
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
