services:

  spring-boot-app:
    container_name: gpc-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Dserver.port=8080

  frontend:
    container_name: gpc-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
